version: '3'

services:
 db:
   container_name: projectudemydb_container
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: projectudemydb
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: senha1
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5455:5432"
   volumes:
     - ./postgres_data:/var/lib/postgresql/data
